default_platform(:ios)

platform :ios do

  before_all do
    ENV["FASTLANE_XCODEBUILD_SETTINGS_TIMEOUT"] = "120"
  end

  desc "Load ASC API Key information to use in subsequent lanes"
  lane :load_asc_api_key do
   app_store_connect_api_key(
     key_id: ENV["ASC_KEY_ID"],
     issuer_id: ENV["ASC_ISSUER_ID"],
     key_content: ENV["ASC_KEY"],
     in_house: false # detecting this via ASC private key not currently supported
   )
  end

  desc "List Provisioning Profiles" 
  lane :list_profiles do
    sh "security find-identity -v -p codesigning" 
  end

  desc "Install cocoapods"
    lane :install_pods do
      cocoapods(
          clean: true,
          use_bundle_exec: false,
          repo_update: true,
          podfile: "#{ENV['IOS_BUILD_PATH']}/iOS/Podfile"
    )
  end

  desc "Build and upload to TestFlight"
    lane :build_upload_testflight do            
        # Основная версия задаётся вручную через переменную MAJOR_VERSION
        major_version = ENV["MAJOR_VERSION"] || "1.0"
        last_uploaded_build = (ENV["LAST_UPLOADED_BUILD_NUMBER"] || "0").to_i
        new_minor = last_uploaded_build + 1
        new_build_number = "#{major_version}.#{new_minor}"
        #increment_build_number(build_number: new_build_number)
      load_asc_api_key
      setup_ci
      match(
        type: 'appstore',
        readonly: false,
        verbose: true,
        force: true,
        git_basic_authorization: ENV["MATCH_GIT_BASIC_AUTHORIZATION"]
      )
      list_profiles
      sync_code_signing(
        type: "appstore",
        readonly: true
      )      

      code_sign_identity = sh("security find-identity -v -p codesigning | grep 'Apple Distribution' | head -n 1 | awk -F '\"' '{print $2}'").strip
      update_code_signing_settings(
        path: "#{ENV['IOS_BUILD_PATH']}/iOS/Unity-iPhone.xcodeproj",
        use_automatic_signing: false,
        team_id: ENV["TEAM_ID"],
        targets: ENV["XC_TARGET_NAME"],        
        code_sign_identity: code_sign_identity,
        sdk: "iphoneos*",
        profile_name: "match AppStore #{ENV["BUNDLE_IDENTIFIER"]}",        
      )
      update_code_signing_settings(
        path: "#{ENV['IOS_BUILD_PATH']}/iOS/Unity-iPhone.xcodeproj",
        use_automatic_signing: false,
        team_id: ENV["TEAM_ID"],
        targets: "notifications",        
        code_sign_identity: code_sign_identity,
        sdk: "iphoneos*",
        profile_name: "match AppStore #{ENV["BUNDLE_IDENTIFIER"]}.notifications",        
      ) 

      install_pods

      build_app(
        workspace: "#{ENV['IOS_BUILD_PATH']}/iOS/Unity-iPhone.xcworkspace",
        #project: "#{ENV['IOS_BUILD_PATH']}/iOS/Unity-iPhone.xcodeproj",
        scheme: ENV["XC_TARGET_NAME"],
        xcargs: "-allowProvisioningUpdates",
        export_team_id: ENV["TEAM_ID"],
        verbose: true,
        export_options: {
            method: 'app-store',
            uploadBitcode: false, 
            compileBitcode: false,
        }
      )
      upload_to_testflight(
        apple_id: "6756005975",
        skip_waiting_for_build_processing: true)      
      sh("echo 'LAST_UPLOADED_BUILD_NUMBER=#{new_build_number}' >> $GITHUB_ENV")
   end
end