name: Download Artifact From Another Workflow

on:
  workflow_dispatch:

jobs:
  download-artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate MATCH_GIT_BASIC_AUTHORIZATION
        run: |
          echo -n "NikDyr:${GH_PAT}" | base64 > base64.txt
          echo "MATCH_GIT_BASIC_AUTHORIZATION=$(cat base64.txt)" >> $GITHUB_ENV
        env:
          GH_PAT: ${{ secrets.GH_PAT }}

      - name: Download artifact
        uses: dawidd6/action-download-artifact@v3
        with:
          github_token: ${{ env.MATCH_GIT_BASIC_AUTHORIZATION }}
          workflow: unity_ios.yml                # имя workflow, где создаётся артефакт
          workflow_conclusion: success
          branch: unity-ios                     # ветка, где запускался workflow
          name: Build-iOS                    # имя артефакта
          path: ./artifact                   # куда распаковать

      - name: List artifact contents
        run: ls -la ./artifact

      - name: Do something with artifact
        run: |
          # Ваши действия с ./artifact
          echo "Processing artifact..."